source settings/config.sh

LOCAL_IP=$GLOBAL_LOCAL_IP
METADATA_IP=$GLOBAL_METADATA_IP
LOAD_BALANCER_IP=$GLOBAL_LOAD_BALANCER_IP

CACHE_SIZE=4096000000
CACHE_BLOCK_SIZE=4096000

CACHE_PORT=$GLOBAL_CAHCE_PORT_FOR_SERVER
METADATA_PORT=$GLOBAL_METADATA_PORT
LOAD_BALANCER_PORT=$GLOBAL_LOAD_BALANCER_PORT_FOR_CACHE

echo "Local IP: $LOCAL_IP"
echo "Cache port: $CACHE_PORT"
echo "Metadata IP: $METADATA_IP"
echo "Metadata port: $METADATA_PORT"
echo "Load balancer IP: $LOAD_BALANCER_IP"
echo "Load balancer port: $LOAD_BALANCER_PORT"
echo "Cache size: $CACHE_SIZE"
echo "Cache block size: $CACHE_BLOCK_SIZE"

sleep 1
FI_EFA_ENABLE_SHM_TRANSFER=0 ./build/bin/cache $LOCAL_IP $CACHE_PORT $METADATA_IP $METADATA_PORT $LOAD_BALANCER_IP $LOAD_BALANCER_PORT cachecache $CACHE_SIZE $CACHE_BLOCK_SIZE