source settings/config.sh

CONTROLLER_IP=$GLOBAL_CONTROLLER_IP
CONTROLLER_PORT=$GLOBAL_CONTROLLER_PORT_FOR_SUBSCRIBER
LOAD_BALANCER_IP=$GLOBAL_LOAD_BALANCER_IP
LOAD_BALANCER_PORT=$GLOBAL_LOAD_BALANCER_PORT_FOR_CLIENT
NUM_REQUEST=${1:-$GLOBAL_NUM_REQUEST}

python build/bin/client_max_inference.py $CONTROLLER_IP $CONTROLLER_PORT $LOAD_BALANCER_IP $LOAD_BALANCER_PORT $NUM_REQUEST